### ISSUE TITLE
ICUCompatApi23 addLikelySubtags Missing

### ISSUE THREAD

**Issue by richard-instil** [satyan/sugar#391]
When running sugar 1.3.1 in basic android app with only support library dependencies on device, or emulator, running Jellybean 4.2.2 get the error shown below. No issue running on Lollipop. Looks like a support library issue - opened as ticket against Android. More details on reproduction steps in ticket [188047](https://code.google.com/p/android/issues/detail?id=188047)

  Caused by: java.lang.NoSuchMethodException: addLikelySubtags [class java.util.Locale]
            at java.lang.Class.getConstructorOrMethod(Class.java:460)
            at java.lang.Class.getMethod(Class.java:915)
            at android.support.v4.text.ICUCompatApi23.<clinit>(ICUCompatApi23.java:35)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:217)
            at com.orm.SugarDb.getDomainClass(SugarDb.java:60)
            at com.orm.SugarDb.getDomainClasses(SugarDb.java:41)
            at com.orm.SugarDb.createDatabase(SugarDb.java:104)
            at com.orm.SugarDb.onCreate(SugarDb.java:100)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
            at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
            at com.orm.Database.getDB(Database.java:18)
            at com.orm.SugarRecord.save(SugarRecord.java:45)

**Comment by thedamfr** [comment]
Did you find any work around ?

**Comment by Ewg777** [comment]
+1

**Comment by nozay** [comment]
+1
15 Eki 2015 11:12 tarihinde "Evgeniy" <notifications@github.com> yazdı:

**Comment by thedamfr** [comment]
FYI 
I think I fixed it by upgrading gradle tools.
Love

**Comment by Ewg777** [comment]
@thedamfr to which version?

**Comment by thedamfr** [comment]
buildToolsVersion '23.0.1'

**Comment by fcelarino** [comment]
Hi guys. I updated my buildToolsVersion to 23.0.1 and I still have the same problem. Somebody figured out how to fix it?

**Comment by Ewg777** [comment]
sugar 1.4 has same error

**Comment by antoniocanaveral** [comment]
Have the same error on Lollipop targetSdkVersion 22, buildToolsVersion "22.0.0", compile 'com.github.satyan:sugar:1.3.1' Was working fine till last AndroidStudio Upgrade

**Comment by Ewg777** [comment]
Try to config DOMAIN_PACKAGE_NAME in AndroidManifest.xml (http://satyan.github.io/sugar/getting-started.html)

**Comment by Ovadia-B** [comment]
I just fixed that
https://github.com/satyan/sugar/pull/411/files

The master branch support multidex but filtering by domain package name was removed.

**Comment by issyzac** [comment]
Sorry, has it been merged with the master branch already? @Ovadia-B

**Comment by jota-leal** [comment]
What @Ewg777 said did the trick for me.
I had the DOMAIN_PACKAGE_NAME meta-data tag in AndoidManifest.xml but the android:name attribute was misspelled. Correcting that stopped the error in Jelly Bean.

**Comment by Ovadia-B** [comment]
I already had those meta tags and still had the problem

**Comment by issyzac** [comment]
The meta tags worked for me too, if you are still getting the error try and make sure the meta tags are inside  <application></application> tags and not outside.

**Comment by JusticeRage** [comment]
This may have been closed too quickly.
I'm encountering this bug too on 4.4 devices using 23.0.2 build tools. Meta tags are correctly specified inside application tags. I run the latest commit of SugarORM.

Here is a full stack trace:
```
java.lang.ExceptionInInitializerError
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:251)
at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:265)
at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:249)
at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:42)
at com.orm.SugarDb.onCreate(SugarDb.java:26)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
at com.orm.SugarDb.getDB(SugarDb.java:36)
at com.orm.SugarRecord.getSugarDataBase(SugarRecord.java:34)
at com.orm.SugarRecord.find(SugarRecord.java:171)
at com.orm.SugarRecord.find(SugarRecord.java:157)
at fr.kwiatkowski.apktrack.model.InstalledApp.find_app(InstalledApp.java:201)
at fr.kwiatkowski.apktrack.model.InstalledApp.detect_new_version(InstalledApp.java:160)
at fr.kwiatkowski.apktrack.MainActivity$1.run(MainActivity.java:81)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalStateException: java.lang.NoSuchMethodException: addLikelySubtags [class java.util.Locale]
at android.support.v4.text.ICUCompatApi23.<clinit>(ICUCompatApi23.java:38)
... 16 more
Caused by: java.lang.NoSuchMethodException: addLikelySubtags [class java.util.Locale]
at java.lang.Class.getConstructorOrMethod(Class.java:472)
at java.lang.Class.getMethod(Class.java:857)
at android.support.v4.text.ICUCompatApi23.<clinit>(ICUCompatApi23.java:35)
... 16 more
java.lang.IllegalStateException: java.lang.NoSuchMethodException: addLikelySubtags [class java.util.Locale]
at android.support.v4.text.ICUCompatApi23.<clinit>(ICUCompatApi23.java:38)
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:251)
at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:265)
at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:249)
at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:42)
at com.orm.SugarDb.onCreate(SugarDb.java:26)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
at com.orm.SugarDb.getDB(SugarDb.java:36)
at com.orm.SugarRecord.getSugarDataBase(SugarRecord.java:34)
at com.orm.SugarRecord.find(SugarRecord.java:171)
at com.orm.SugarRecord.find(SugarRecord.java:157)
at fr.kwiatkowski.apktrack.model.InstalledApp.find_app(InstalledApp.java:201)
at fr.kwiatkowski.apktrack.model.InstalledApp.detect_new_version(InstalledApp.java:160)
at fr.kwiatkowski.apktrack.MainActivity$1.run(MainActivity.java:81)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NoSuchMethodException: addLikelySubtags [class java.util.Locale]
at java.lang.Class.getConstructorOrMethod(Class.java:472)
at java.lang.Class.getMethod(Class.java:857)
at android.support.v4.text.ICUCompatApi23.<clinit>(ICUCompatApi23.java:35)
... 16 more
java.lang.NoSuchMethodException: addLikelySubtags [class java.util.Locale]
at java.lang.Class.getConstructorOrMethod(Class.java:472)
at java.lang.Class.getMethod(Class.java:857)
at android.support.v4.text.ICUCompatApi23.<clinit>(ICUCompatApi23.java:35)
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:251)
at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:265)
at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:249)
at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:42)
at com.orm.SugarDb.onCreate(SugarDb.java:26)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
at com.orm.SugarDb.getDB(SugarDb.java:36)
at com.orm.SugarRecord.getSugarDataBase(SugarRecord.java:34)
at com.orm.SugarRecord.find(SugarRecord.java:171)
at com.orm.SugarRecord.find(SugarRecord.java:157)
at fr.kwiatkowski.apktrack.model.InstalledApp.find_app(InstalledApp.java:201)
at fr.kwiatkowski.apktrack.model.InstalledApp.detect_new_version(InstalledApp.java:160)
at fr.kwiatkowski.apktrack.MainActivity$1.run(MainActivity.java:81)
at java.lang.Thread.run(Thread.java:841)
```

I tried applying @Ovadia-B's patch, but it caused `android.database.sqlite.SQLiteException`s instead (no such table).

**Comment by Ovadia-B** [comment]
@JusticeRage You need to increase the VERSION meta tag or reinstall the app.

**Comment by JusticeRage** [comment]
@Ovadia-B Wow, this actually worked. I never had the problem on my device, but I was reproducing it on Amazon's AWS device farm which I assumed (and still kinda do) were wiped clean after each test run. Increasing the VERSION meta tag worked, but I'm confused as to why. Thanks for your help anyway, and I hope that your patch makes it to master.

**Comment by nicolabeghin** [comment]
I confirm the @Ovadia-B patch fixes the issue but only partially, meaning that classes inside the defined package (DOMAIN_PACKAGE_NAME) are correctly handled, while the one outside BUT marked with @Table annotation are not. This was working before (I have a production app working like this)

**Comment by LisitaEugen** [comment]
Putting meta-data tags in inside application helped me. Thanks to @issyzac

**Comment by qrazhan** [comment]
I'm still running into this issue on 4.4 devices. I'm on Sugar 1.4.

Stack trace: 

`Process: com.thevotinggame.thevotinggame, PID: 8621
                                                                               java.lang.ExceptionInInitializerError
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at java.lang.Class.forName(Class.java:251)
                                                                                   at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:270)
                                                                                   at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:254)
                                                                                   at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:37)
                                                                                   at com.orm.SugarDb.onCreate(SugarDb.java:26)
                                                                                   at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
                                                                                   at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
                                                                                   at com.orm.SugarDb.getDB(SugarDb.java:36)
                                                                                   at com.orm.SugarRecord.save(SugarRecord.java:360)
                                                                                   at com.thevotinggame.thevotinggame.classes.Deck.createNewDeck(Deck.java:47)
                                                                                   at com.thevotinggame.thevotinggame.activities.TheVotingGameApplication.onCreate(TheVotingGameApplication.java:43)
                                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
                                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: java.lang.IllegalStateException: java.lang.NoSuchMethodException: addLikelySubtags [class java.util.Locale]
                                                                                   at android.support.v4.text.ICUCompatApi23.<clinit>(ICUCompatApi23.java:38)
                                                                                   at java.lang.Class.classForName(Native Method) 
                                                                                   at java.lang.Class.forName(Class.java:251) 
                                                                                   at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:270) 
                                                                                   at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:254) 
                                                                                   at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:37) 
                                                                                   at com.orm.SugarDb.onCreate(SugarDb.java:26) 
                                                                                   at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252) 
                                                                                   at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164) 
                                                                                   at com.orm.SugarDb.getDB(SugarDb.java:36) 
                                                                                   at com.orm.SugarRecord.save(SugarRecord.java:360) 
                                                                                   at com.thevotinggame.thevotinggame.classes.Deck.createNewDeck(Deck.java:47) 
                                                                                   at com.thevotinggame.thevotinggame.activities.TheVotingGameApplication.onCreate(TheVotingGameApplication.java:43) 
                                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007) 
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344) 
                                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                                Caused by: java.lang.NoSuchMethodException: addLikelySubtags [class java.util.Locale]
                                                                                   at java.lang.Class.getConstructorOrMethod(Class.java:472)
                                                                                   at java.lang.Class.getMethod(Class.java:857)
                                                                                   at android.support.v4.text.ICUCompatApi23.<clinit>(ICUCompatApi23.java:35)
                                                                                   at java.lang.Class.classForName(Native Method) 
                                                                                   at java.lang.Class.forName(Class.java:251) 
                                                                                   at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:270) 
                                                                                   at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:254) 
                                                                                   at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:37) 
                                                                                   at com.orm.SugarDb.onCreate(SugarDb.java:26) 
                                                                                   at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252) 
                                                                                   at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164) 
                                                                                   at com.orm.SugarDb.getDB(SugarDb.java:36) 
                                                                                   at com.orm.SugarRecord.save(SugarRecord.java:360) 
                                                                                   at com.thevotinggame.thevotinggame.classes.Deck.createNewDeck(Deck.java:47) 
                                                                                   at com.thevotinggame.thevotinggame.activities.TheVotingGameApplication.onCreate(TheVotingGameApplication.java:43) 
                                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007) 
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344) 
                                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) `
