### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/collect/MapMaker

### ISSUE THREAD

**Issue by HendraAnggrian** [satyan/sugar#464]
I followed the code from example:

```java
public class ClientApp extends android.app.Application {
    @Override
    public void onCreate() {
        super.onCreate();
        SugarContext.init(this);
    }

    @Override
    public void onTerminate() {
        super.onTerminate();
        SugarContext.terminate();
    }
}
```

I got `java.lang.NoClassDefFoundError` from `SugarContext.init(this)`
On top of that, I also receive:

D/sugar: Couldn't find config value: DATABASE
D/sugar: Couldn't find config value: QUERY_LOG
D/sugar: Couldn't find config value: VERSION

I am very sure I have setup the meta-data tag similar to the example. What could be the issue?

**Comment by sibeliusseraphini** [comment]
@HendraAnggrian are u using 1.3 ? or 1.4? or master version?

**Comment by HendraAnggrian** [comment]
I am using 1.4 jar version

**Comment by haoliguo** [comment]
how to solve it?

**Comment by HendraAnggrian** [comment]
@haoliguo are you experiencing the same issue? I'm temporarily switching back to v1.3

**Comment by sibeliusseraphini** [comment]
@HendraAnggrian your code is the same: https://github.com/satyan/sugar/blob/master/library/src/main/java/com/orm/SugarApp.java, maybe it is a problem with your manifest or a problem with multidex

**Comment by LarryLGHao** [comment]
@HendraAnggrian     the jar1.4 still can not run~Now I use the  latest libary,the bug is fixed~ And I try to use "compile 'com.github.satyan:sugar:1.4'" int the AS,but get the error "...finished with non-zero exit value 2",Should be some jar repeated,then I remove the repeated when I found,but the error still exist~

**Comment by hilaryhar** [comment]
do anybody had  solved this problem ?

**Comment by hilaryhar** [comment]
had anybody solved this problem?

**Comment by hendraanggrian** [comment]
@hilaryhar yes it is also still happening with me with v1.4. I managed to solved the issue by extending SugarApp instead of android.app.Application. But also make sure that those meta tags in your manifest.xml are inside the application tag, not outside.

**Comment by richdyang** [comment]
+1

I still have this issue on v1.5
